export const Asociados = [
    {
        id:1,
        name:'google',
        image:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Google_logo_%282010-2013%29.svg/2560px-Google_logo_%282010-2013%29.svg.png'
    },
    {
        id:2,
        name:'amazon',
        image:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/2560px-Amazon_logo.svg.png'
    },
    {
        id:3,
        name:'rappi',
        image:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Rappi_logo.svg/2560px-Rappi_logo.svg.png'
    },
    {
        id:4,
        name:'facebook',
        image:'https://1000marcas.net/wp-content/uploads/2019/12/Facebook-logo.png'
    },
    {
        id:5,
        name:'linkedin',
        image:'https://1000marcas.net/wp-content/uploads/2020/01/Logo-Linkedin.png'
    },
    {
        id:6,
        name:'apple',
        image:'https://www.vectorlogo.zone/logos/apple/apple-ar21.png'
    },
    {
        id:7,
        name:'instagram',
        image:'https://www.shutterstock.com/image-photo/bangkok-thailand-may-14-2016-260nw-435629701.jpg'
    },
    
]

export const Asociados2 = [
    {
        id:1,
        name:'globant',
        image:'https://statics.globant.com/production/public/2022-08/globant-logo.jpg'
    },
    {
        id:2,
        name:'uber',
        image:'https://1000marcas.net/wp-content/uploads/2019/12/UBER-Logo.jpg'
    },
    {
        id:3,
        name:'platzi',
        image:'https://upload.wikimedia.org/wikipedia/commons/3/32/Platzi.jpg'
    },
    {
        id:4,
        name:'mercado libre',
        image:'https://kineo.com/es/glide/containers/main/case_studies_images/Mercado_Libre/meli_case-study-logo-colour.png/d560984a679a4738412487af916cde1d.png'
    },
    {
        id:5,
        name:'fizer',
        image:'https://1000marcas.net/wp-content/uploads/2021/05/Pfizer-logo.png'
    },
    {
        id:6,
        name:'adcenture',
        image:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Accenture.svg/2560px-Accenture.svg.png'
    },
    {
        id:7,
        name:'doulingo',
        image:'https://1000marcas.net/wp-content/uploads/2021/02/Logo-Duolingo.png'
    },
    
]